# Generated by Django 4.2.7 on 2025-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scooters/'),
        ),
    ]
